### ISSUE TITLE
test compatibility with Kafka 0.11.x, 1.x

### ISSUE THREAD

**Issue by jamiealquiza** [DataDog/kafka-kit#129]
Test for full compatibility across the latest versions of Kafka.

**Comment by agolomoodysaada** [comment]
topicmappr works fine with kafka 1.x for me

**Comment by jamiealquiza** [comment]
@agolomoodysaada Great to hear. From my initial look at the internal data structures that are interacted with through topicmappr, the format hasn't changed. Would love to hear if any snags are encountered.

**Comment by klDen** [comment]
Hi, does topicmappr works with Kafka 2.x ?

**Comment by jamiealquiza** [comment]
> Hi, does topicmappr works with Kafka 2.x ?

@klDen It does, we actively use it entirely with 2.x in production now.
