### ISSUE TITLE
Broker ID 0 is excluded

### ISSUE THREAD

**Issue by WheresAlice** [DataDog/kafka-kit#225]
When running topicmappr with the following command:

`./topicmappr rebuild --brokers 0,1,2,3,4,5,6 --topics test_topic [...]`

It is excluding the broker with ID zero:

```
Broker change summary:
  Replacing 0, added 0, missing 0, total count changed by 0

[...]

Broker distribution:
  degree [min/max/avg]: 5/5/5.00 -> 5/5/5.00
  -
  Broker 1 - leader: 4, follower: 8, total: 12
  Broker 2 - leader: 2, follower: 7, total: 9
  Broker 3 - leader: 2, follower: 11, total: 13
  Broker 4 - leader: 4, follower: 8, total: 12
  Broker 5 - leader: 5, follower: 3, total: 8
  Broker 6 - leader: 3, follower: 3, total: 6
```

**Comment by alexcurtin** [comment]
@jamiealquiza what is the workaround for this?

**Comment by benoahriz** [comment]
running into this as well.  In kubernetes statefulsets index starts at 0 so if you rely on the built in naming of a stateful set kafka-0 or the equivalent will always exist so it would be ideal to not skip 0.  Going to dig into this a little more...

**Comment by jamiealquiza** [comment]
0 was chosen initially because it's the uninitialized int value used particularly for the `ID` field in the [Broker](https://github.com/DataDog/kafka-kit/blob/master/kafkazk/brokers.go#L77) type in the `kafkazk` package. Additionally, my setups have always started at ID 1000.

I'll look into switching this to use the int max value instead; this shouldn't be a problem.

**Comment by jamiealquiza** [comment]
👋 hi again friends. I just pushed this test branch which changes the internally reserved 'stub broker' ID from 0 to the int max: https://github.com/DataDog/kafka-kit/tree/jamie/stub-broker-id.

Please take note this is *test* branch that I've just made pass local tests, but it may have some quirks that I haven't accounted for. I'd suggest not using this for production systems quite yet. Feedback would be useful!

**Comment by benoahriz** [comment]
going to try this out and see what happens.  Thanks!

**Comment by benoahriz** [comment]
tried running this against a test cluster and seeing this 

```
Broker change summary:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1211b7d]

goroutine 1 [running]:
github.com/DataDog/kafka-kit/cmd/topicmappr/commands.ensureBrokerMetrics(0x1494020, 0xc000093a40, 0xc000266090)
	/Users/brizkowsky/go-workspace/src/github.com/DataDog/kafka-kit/cmd/topicmappr/commands/metadata.go:57 +0xdd
github.com/DataDog/kafka-kit/cmd/topicmappr/commands.rebuild(0x1494020, 0xc0000c0230, 0x0, 0x7)
	/Users/brizkowsky/go-workspace/src/github.com/DataDog/kafka-kit/cmd/topicmappr/commands/rebuild.go:138 +0xa66
github.com/spf13/cobra.(*Command).execute(0x1494020, 0xc0000c01c0, 0x7, 0x7, 0x1494020, 0xc0000c01c0)
	/Users/brizkowsky/go-workspace/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1494280, 0xc0000ba300, 0x12aa0d5, 0xc)
	/Users/brizkowsky/go-workspace/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1494280, 0x12a98f5, 0xa)
	/Users/brizkowsky/go-workspace/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/DataDog/kafka-kit/cmd/topicmappr/commands.Execute()
	/Users/brizkowsky/go-workspace/src/github.com/DataDog/kafka-kit/cmd/topicmappr/commands/root.go:19 +0x5d
main.main()
	/Users/brizkowsky/go-workspace/src/github.com/DataDog/kafka-kit/cmd/topicmappr/main.go:6 +0x20```

**Comment by jamiealquiza** [comment]
Just pushed another commit that may resolve this; I'll take a closer look in the morning (and will also more thoroughly test this branch)

**Comment by efpe** [comment]
I tested it and it seems to be working. 

```
/home/ec2-user/go/src/github.com/DataDog/kafka-kit/cmd/topicmappr/topicmappr rebuild --brokers "0,2,11" --zk-addr $zk --zk-prefix chroot --topics hello

Topics:
  hello

Broker change summary:
  Broker 1 marked for removal
  -
  Replacing 1, added 0, missing 0, total count changed by -1

Action:
  Shrinking topic by 1 broker(s)
[...]
```

The generated JSON works as it should.

**Comment by benoahriz** [comment]
I also tested and seems to have generated a valid plan.  I didn't run it yet but the output seems to have worked fine including broker 0

**Comment by benoahriz** [comment]
Did some more testing on this on a live cluster and seems ok.  Didn't have any issues rebalancing evenly across the cluster.

**Comment by efpe** [comment]
Any news on this? We would be very happy to see this merged :)

Thank you for the effort!
