### ISSUE TITLE
[toppicmappr] Drain an entire node 

### ISSUE THREAD

**Issue by williamhammond** [DataDog/kafka-kit#243]
There are situations in which i want to gracefully decommission a broker. Currently it seems like what I'd need to is to generate reassignment files per each topic and run reassign-partitions. This is very time consuming if you have a lot of topics. Would it be possible automate the movement of multiple topics with toppicmappr?

**Comment by jamiealquiza** [comment]
This exists! 

- The `--topics` input takes lists, optionally including regex: `--topics "topic1,topic2,topics_*"`
- The `--out-file` param will create a merged map of all of the individually created maps per topic
- Optional: `--skip-no-ops` generates a map that only includes partitions being changed (Kafka processes this more quickly)

Typically, what I do to drain a single node:

Let's say we have two topics `a` and `b` where all partitions are held by brokers 1001, 1002, 1003, 1004. We can drain 1003 with:

```
$ topicmappr rebuild --topics "a,b" --brokers 1001,1002,1004 --skip-no-ops --out-file combined
```

This will produce a `combined.json` file that includes partition movements for bot `a` and `b`, which can be applied in a single reassign partitions call.

**Comment by williamhammond** [comment]
Great! I didn't realize that `--out-file` combines them all into one. Going to close the issue.
