### ISSUE TITLE
Invalid API or app key

### ISSUE THREAD

**Issue by KSI47** [DataDog/kafka-kit#318]
After configuring the dd-agent in my broker host, and starting dd-agent service, I can check my metrics data from the dd webui dashboard, but i'm trying to use topicmappr's storage placement strategy, for that i need metrics fetcher to fetch for those metrics from the datadog API, and when i launch metricsfetcher binary, after setting the api-key and app-key (copied from the dd webui session) as command line options, i always get the error Invalid API or app key.

**Comment by jamiealquiza** [comment]
Can you check and ensure that they're not swapped (ie setting the app key in place of the api key)? Also, I have another tool called [ddq](https://github.com/jamiealquiza/ddq) that uses the same client library. Can you try this with your keys?

**Comment by KSI47** [comment]
same issue with the proposed tool, i think it's because i'm using the bad keys for the API, i used the fast command to launch my datadog-agent, i'm using the webUI to retrieve the keys, is there another way to know what is the key for my API to use ?

**Comment by jamiealquiza** [comment]
It's best to try and generate a new API key and App key and trying that.
