### ISSUE TITLE
topicmappr v4.2.0 insists on requiring `--leader-evac-topics` and `--leader-evac-brokers`

### ISSUE THREAD

**Issue by rocketraman** [DataDog/kafka-kit#425]
Seemingly no matter what parameters are provided to topicmappr v4.2.0, it produces the output:

```
topicmappr rebuild --brokers "-2" --topics foo --kafka-addr $bsserver

[ERROR] --leader-evac-topics and --leader-evac-brokers must both be specified for leadership evacuation.

```

The same exact command works fine on 3.18.1.

**Comment by elukey** [comment]
@zrosenberg @jamiealquiza Hi! I am facing the same issue, and I noticed https://github.com/DataDog/kafka-kit/pull/379. I didn't find docs about the new functionality, but indeed the two evac parameters seem optional from a quick glance at the help menu, but in reality they are not. Could you please clarify how to use them?

**Comment by elukey** [comment]
The 4.2 release came before https://github.com/DataDog/kafka-kit/pull/417/files, that seems to fix the issue.

**Comment by jamiealquiza** [comment]
Apologies, just noticed this issue and taking a look

**Comment by jamiealquiza** [comment]
Tagged `v4.2.1`
